/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

public class ConsultaGeneral extends javax.swing.JDialog {
    


    /**
     * Creates new form ConsultaGeneral
     */
    public ConsultaGeneral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsGral = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de todas las personas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtConsGral.setEditable(false);
        txtConsGral.setColumns(20);
        txtConsGral.setRows(5);
        txtConsGral.setDragEnabled(true);
        jScrollPane2.setViewportView(txtConsGral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String nombre, domicilio, telefono;
        int cont = PruebaAgenda.agenda.getCont();
        for(int x=0; x<cont; x++){
            nombre =  PruebaAgenda.agenda.getPersona(x).getNombre();
            domicilio = PruebaAgenda.agenda.getPersona(x).getDomicilio();
            telefono = PruebaAgenda.agenda.getPersona(x).getTelefono();
            txtConsGral.setText(txtConsGral.getText() + 
                    "Persona " + String.valueOf(x+1) + "\n" + 
                     "Nombre: " + nombre + "\n" + 
                    "Domicilio: " + domicilio + "\n" + 
                    "Telefono:" + telefono + "\n\n" );
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtConsGral;
    // End of variables declaration//GEN-END:variables
}
