
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import  javax.swing.JFrame;
import javax.swing.JOptionPane;
        
        
public class PruebaAgenda extends javax.swing.JFrame {
    
    public static Agenda agenda;
    int cantidadPersonas;

    /**
     * Creates new form PruebaAgenda
     */
    public PruebaAgenda() {
        initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcSalir = new javax.swing.JMenuItem();
        menuAcciones = new javax.swing.JMenu();
        opcAgregar = new javax.swing.JMenuItem();
        opcConsInd = new javax.swing.JMenuItem();
        opcConsGral = new javax.swing.JMenuItem();
        opcModificar = new javax.swing.JMenuItem();
        opcEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda personal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuArchivo.setText("Archivo");
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(opcSalir);

        jMenuBar1.add(menuArchivo);

        menuAcciones.setText("Acciones");

        opcAgregar.setText("Agregar persona");
        opcAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAgregarActionPerformed(evt);
            }
        });
        menuAcciones.add(opcAgregar);

        opcConsInd.setText("Consultar persona");
        opcConsInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsIndActionPerformed(evt);
            }
        });
        menuAcciones.add(opcConsInd);

        opcConsGral.setText("Consultar todas las personas");
        opcConsGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsGralActionPerformed(evt);
            }
        });
        menuAcciones.add(opcConsGral);

        opcModificar.setText("Modificar persona");
        opcModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcModificarActionPerformed(evt);
            }
        });
        menuAcciones.add(opcModificar);

        opcEliminar.setText("Eliminar persona");
        opcEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcEliminarActionPerformed(evt);
            }
        });
        menuAcciones.add(opcEliminar);

        jMenuBar1.add(menuAcciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        JOptionPane.showMessageDialog(this, 
                        "Creado por: Juarez Magaña Jose David" ,
                        "Finalizar programa" ,
                        JOptionPane.INFORMATION_MESSAGE);  
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
            
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            cantidadPersonas = Integer.parseInt(JOptionPane.showInputDialog(this,
                    "Ingrese la cantidad de personas que contendra la agenda ",
                            "Inicializando la agenda"));
           agenda = new Agenda(cantidadPersonas);
    }//GEN-LAST:event_formWindowOpened

    private void opcAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAgregarActionPerformed
        if (agenda.getCont() < cantidadPersonas){   
        AgregarPersona ap  =  new AgregarPersona(this, true);
           ap.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, 
                        "No hay espacio para registrar mas  personas" ,
                        "Agenda llena" ,
                        JOptionPane.INFORMATION_MESSAGE);
            
        }   
    }//GEN-LAST:event_opcAgregarActionPerformed

    private void opcConsIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsIndActionPerformed
            if (agenda.getCont() > 0 ) {
                ConsultarPersona cp  =  new ConsultarPersona(this, true);
                cp.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, 
                        "No se han registrado personas en la agenda " ,
                        "Agenda vacia" ,
                        JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_opcConsIndActionPerformed

    private void opcModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcModificarActionPerformed
        if (agenda.getCont() > 0 ) {
            ModificarPersona mp = new ModificarPersona(this, true);
            mp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, 
                "No se han registrado personas en la agenda " ,
                "Agenda vacia" ,
                JOptionPane.INFORMATION_MESSAGE);
        }    
    }//GEN-LAST:event_opcModificarActionPerformed

    private void opcEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcEliminarActionPerformed
       if (agenda.getCont() > 0 ) {
            EliminarPersona ep  = new EliminarPersona(this, true);
            ep.setVisible(true);
       }else {
            JOptionPane.showMessageDialog(this, 
                "No se han registrado personas en la agenda " ,
                "Agenda vacia" ,
                JOptionPane.INFORMATION_MESSAGE);  
       }     
    }//GEN-LAST:event_opcEliminarActionPerformed

    private void opcConsGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsGralActionPerformed
        if (agenda.getCont() > 0 ) {
            ConsultaGeneral cg = new  ConsultaGeneral(this, true);
            cg.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, 
                "No se han registrado personas en la agenda " ,
                "Agenda vacia" ,
                JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_opcConsGralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAcciones;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem opcAgregar;
    private javax.swing.JMenuItem opcConsGral;
    private javax.swing.JMenuItem opcConsInd;
    private javax.swing.JMenuItem opcEliminar;
    private javax.swing.JMenuItem opcModificar;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}

